version: '3'

services:
  rca-analyzer:
    image: msv-analyzer:1.0
    container_name: "rca-analyzer"
    hostname: rca-analyzer-host
    environment:
      - FORBIDDEN_WORDS_FILE=/mnt/analyzer/forbbiden.csv
      - UPDATER_QUEUE_NAME=rca-status-updates
      - SUSPICIOUS_QUEUE_NAME=rca-suspicious-records
      - RCA-EXCHANGE_NAME=rca-direct-exchange
      - RCA-MESSAGING-RETRIES=3
      - RCA-MESSAGING-INTERVAL=1000
      - RABBIT_URL=host.docker.internal
    ports:
      - "8082:8082"
    networks:
      - my-network
    volumes:
      - D:/Development/PROJECTS/10.REACTIVE-CHAT-ANALYZER/analyzer:/mnt/analyzer
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 120M
        reservations:
          cpus: 0.5
          memory: 20M

networks:
  my-network:
    driver: bridge