version: '3.8'

services:
  rca-rabbitmq:
    image: rabbitmq:3-management
    container_name: rca-rabbitmq
    hostname: rca-rabbit-mq-host
    volumes:
      - D:/Development/PROJECTS/10.REACTIVE-CHAT-ANALYZER/rabbit-volume/rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - D:/Development/PROJECTS/10.REACTIVE-CHAT-ANALYZER/rabbit-volume/rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - D:/Development/PROJECTS/10.REACTIVE-CHAT-ANALYZER/rabbit-volume/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - D:/Development/PROJECTS/10.REACTIVE-CHAT-ANALYZER/rabbit-volume/rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      # Admin management console (http://localhost:15672/) (guest:guest)
      - 15672:15672