version: '3'

services:
  rca-reader:
    image: msv-reader:1.0
    container_name: "rca-reader"
    hostname: rca-reader-host
    environment:
      - MONGODB_URL=host.docker.internal
      - DB_REACTIVE_INTERVAL=1000
      - DB_REACTIVE_LIMIT=10
      - RCA-DB-RETRIES=2
      - RCA-DB-INTERVAL=1000
    ports:
      - "8081:8081"
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 120M
        reservations:
          cpus: 0.5
          memory: 20M

networks:
  my-network:
    driver: bridge